name: 'Amplify Deploy'
on: 
  push:
    branches: 
      - master

jobs:
  test-admin:
    name: test amplify-cli-action
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1

    - name: use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: configure amplify
      uses: ./.github/actions
      with:
        amplify_command: configure
        amplify_env: prod
        project_dir: packages/admin 
        build_command: 'yarn build'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
        
    - name: install, build and test
      run: |
        npm i -g yarn
        cd packages/admin
        yarn install
        # build and test
        # npm run build
        # npm run test
    
    - name: deploy
      uses: ./.github/actions
      with:
        amplify_command: publish
        amplify_env: prod
        project_dir: packages/admin
        build_command: 'yarn build'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
